global:
    scrape_interval:     15s
    evaluation_interval: 15s

scrape_configs:
    -
        job_name: 'prometheus'
        scrape_interval: 10s
        static_configs:
            - targets: ['localhost:9090']

    -
        job_name: 'application'
        scrape_interval: 5s
        static_configs:
            - targets: ['dockerhost:10000']

