version: 2.1

executors:
    docker:
        docker:
            -   image: circleci/golang:1.12
                environment:
                    GOFLAGS: -mod=readonly

commands:
    restore_build_cache:
        description: Restore build cache
        steps:
            -
                restore_cache:
                    name: Restore build dependencies
                    keys:
                        - build-deps-v1-{{ .Branch }}-{{ checksum "Makefile" }}

    restore_go_module_cache:
        description: Restore Go module cache
        steps:
            -
                restore_cache:
                    name: Restore Go module cache
                    keys:
                        - gomod-v1-{{ .Branch }}-{{ checksum "go.sum" }}
                        - gomod-v1-{{ .Branch }}
                        - gomod-v1-master
                        - gomod-v1

    save_build_cache:
        description: Save build cache
        steps:
            -
                save_cache:
                    name: Save build dependencies
                    key: build-deps-v1-{{ .Branch }}-{{ checksum "Makefile" }}
                    paths:
                        - bin/

jobs:
    dependencies:
        executor: docker

        steps:
            - checkout
            - restore_go_module_cache

            -
                run:
                    name: Download Go module cache
                    command: go mod download

            -
                save_cache:
                    name: Save Go module cache
                    key: gomod-v1-{{ .Branch }}-{{ checksum "go.sum" }}
                    paths:
                        - /go/pkg/mod

    unit-tests:
        executor: docker

        steps:
            - checkout
            - restore_build_cache
            - restore_go_module_cache

            -
                run:
                    name: Run tests
                    command: TEST_PKGS=$(echo `go list ./... | circleci tests split`) TEST_REPORT_NAME=results_${CIRCLE_NODE_INDEX}.xml make test

            -
                run:
                    name: Run linter
                    command: make lint

            - save_build_cache

            -
                store_test_results:
                    path: build/test_results/

    integration-tests:
        executor: docker

        steps:
            - checkout
            - restore_build_cache
            - restore_go_module_cache

            -
                run:
                    name: Run integration tests
                    command: TEST_PKGS=$(echo `go list ./... | circleci tests split`) TEST_REPORT_NAME=results_${CIRCLE_NODE_INDEX}.xml make test-integration

            - save_build_cache

            -
                store_test_results:
                    path: build/test_results/

    lint:
        executor: docker

        steps:
            - checkout
            - restore_build_cache
            - restore_go_module_cache

            -
                run:
                    name: Run linter
                    command: make lint

            - save_build_cache

workflows:
    version: 2
    build:
        jobs:
            - dependencies
            - unit-tests:
                  requires:
                      - dependencies
            - integration-tests:
                  requires:
                      - dependencies
            - lint:
                  requires:
                      - dependencies
