apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spotguide-modern-go-application.fullname" . | trunc 59 | trimSuffix "-" }}-env
  labels:
    app.kubernetes.io/name: {{ include "spotguide-modern-go-application.name" . }}
    helm.sh/chart: {{ include "spotguide-modern-go-application.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: {{ include "spotguide-modern-go-application.name" . }}
data:
  {{ .Values.application.envPrefix }}_DATABASE_HOST: {{ include "spotguide-modern-go-application.mysql.host" . | quote }}
  {{ .Values.application.envPrefix }}_DATABASE_PORT: {{ include "spotguide-modern-go-application.mysql.port" . | quote }}
  {{ .Values.application.envPrefix }}_DATABASE_NAME: {{ required "MySQL database is required!" .Values.mysql.database | quote }}
