language: go

dist: xenial

services:
    - docker

go:
    - 1.13.x
    - tip

branches:
    only:
        - master
        - /^v?\d+\.\d+\.\d+(-\S*)?$/

env:
    global:
        - GO111MODULE=on
        - GOFLAGS=-mod=readonly

matrix:
    fast_finish: true
    allow_failures:
        - go: tip

cache:
    directories:
        - bin
        - $HOME/gopath/pkg/mod

install: go mod download

before_script:
    - export VERSION=${TRAVIS_TAG:-$TRAVIS_BRANCH}
    - export $(make varexport-DOCKER_IMAGE)

script:
    - make test
    - make test-integration
    - make lint
    - if [[ $VERSION = "master" ]]; then export DOCKER_LATEST=1; fi
    - make docker
    - make docker-debug

#before_deploy: docker login -u $DOCKER_USER -p $DOCKER_PASS
#
#deploy:
#    provider: script
#    skip_cleanup: true
#    script: docker push $DOCKER_IMAGE
#    on:
#        all_branches: true
#        condition: $TRAVIS_GO_VERSION =~ ^1\.12(\.(x|[0-9]+))?$
